<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5f1d7af5-5e5f-47d9-9c11-96d8e35cf008</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auktionshuset.Application\Auktionshuset.Application.csproj" />
    <ProjectReference Include="..\Auktionshuset.Contracts\Auktionshuset.Contracts.csproj" />
    <ProjectReference Include="..\Auktionshuset.Infrastructure\Auktionshuset.Infrastructure.csproj" />
  </ItemGroup>

  
</Project>
