using Auktionshuset.Application.Abstraction.Admin.Lots;

namespace Auktionshuset.Infrastructure.Service.Lots
{
    /// <summary>
    /// Stores lot images as files in a single folder. File names are always generated by the
    /// server, so a name supplied by a client can never influence the path that is written to.
    /// </summary>
    public sealed class FileSystemLotImageStore : ILotImageStore
    {
        /// <summary>
        /// The extensions the store is allowed to write. The extension always originates from the
        /// verified image header, never from the uploaded file name.
        /// </summary>
        private static readonly HashSet<string> AllowedExtensions =
            new(StringComparer.OrdinalIgnoreCase) { ".jpg", ".png", ".webp" };

        private readonly string _rootPath;

        /// <summary>
        /// Initializes a new instance of the <see cref="FileSystemLotImageStore"/>.
        /// </summary>
        /// <param name="options">The options holding the folder that images are stored in.</param>
        public FileSystemLotImageStore(LotImageStoreOptions options)
        {
            _rootPath = options.RootPath;
        }

        /// <summary>
        /// Writes an image to the store under a generated, path-safe file name.
        /// </summary>
        /// <param name="content">The image bytes to store.</param>
        /// <param name="extension">The extension, including the leading dot, derived from the verified image header.</param>
        /// <returns>The generated file name.</returns>
        /// <exception cref="ArgumentException">Thrown when the extension is not one of the supported image types.</exception>
        public async Task<string> SaveAsync(Stream content, string extension, CancellationToken cancellationToken)
        {
            if (!AllowedExtensions.Contains(extension))
            {
                throw new ArgumentException(
                    $"The image extension '{extension}' is not supported.",
                    nameof(extension));
            }

            Directory.CreateDirectory(_rootPath);

            var fileName = $"{Guid.NewGuid():N}{extension.ToLowerInvariant()}";
            var path = Path.Combine(_rootPath, fileName);

            if (content.CanSeek)
            {
                content.Position = 0;
            }

            await using var target = new FileStream(
                path,
                FileMode.CreateNew,
                FileAccess.Write,
                FileShare.None,
                bufferSize: 81920,
                useAsync: true);

            await content.CopyToAsync(target, cancellationToken);

            return fileName;
        }

        /// <summary>
        /// Removes a stored image.
        /// </summary>
        /// <param name="fileName">The file name previously returned by <see cref="SaveAsync"/>.</param>
        /// <returns><see langword="true"/> when a file was removed; otherwise, <see langword="false"/>.</returns>
        public Task<bool> DeleteAsync(string fileName, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var path = ResolvePath(fileName);

            if (path is null || !File.Exists(path))
            {
                return Task.FromResult(false);
            }

            File.Delete(path);

            return Task.FromResult(true);
        }

        /// <summary>
        /// Resolves a stored file name into an absolute path inside the store folder, rejecting
        /// anything that tries to leave it.
        /// </summary>
        /// <param name="fileName">The stored file name to resolve.</param>
        /// <returns>The absolute path, or <see langword="null"/> when the name is not a bare file name.</returns>
        private string? ResolvePath(string? fileName)
        {
            if (string.IsNullOrWhiteSpace(fileName))
            {
                return null;
            }

            // Only a bare file name is accepted: separators, rooted paths and traversal are refused.
            if (!string.Equals(Path.GetFileName(fileName), fileName, StringComparison.Ordinal)
                || fileName.AsSpan().IndexOfAny('\\', '/', ':') >= 0
                || fileName.Contains("..", StringComparison.Ordinal))
            {
                return null;
            }

            if (!AllowedExtensions.Contains(Path.GetExtension(fileName)))
            {
                return null;
            }

            var root = Path.GetFullPath(_rootPath);
            var path = Path.GetFullPath(Path.Combine(root, fileName));

            return path.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase)
                ? path
                : null;
        }
    }
}
